[2024-07-19T09:09:20.128+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_spark_operator.python_job scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T09:09:20.135+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_spark_operator.python_job scheduled__2024-07-18T00:00:00+00:00 [queued]>
[2024-07-19T09:09:20.135+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-19T09:09:20.152+0000] {taskinstance.py:2217} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-07-18 00:00:00+00:00
[2024-07-19T09:09:20.160+0000] {standard_task_runner.py:60} INFO - Started process 2207 to run task
[2024-07-19T09:09:20.163+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'example_spark_operator', 'python_job', 'scheduled__2024-07-18T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpv3if7hc0']
[2024-07-19T09:09:20.164+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask python_job
[2024-07-19T09:09:20.227+0000] {task_command.py:423} INFO - Running <TaskInstance: example_spark_operator.python_job scheduled__2024-07-18T00:00:00+00:00 [running]> on host e0be4a68a7ce
[2024-07-19T09:09:20.299+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_spark_operator' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-18T00:00:00+00:00'
[2024-07-19T09:09:20.306+0000] {spark_submit.py:271} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-07-19T09:09:20.307+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local --name arrow-spark /plugins/pyspark.py
[2024-07-19T09:09:20.372+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-07-19T09:09:21.674+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-07-19T09:09:21.674+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-07-19T09:09:21.675+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-07-19T09:09:21.675+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-07-19T09:09:21.675+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-07-19T09:09:21.675+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-07-19T09:09:21.675+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-07-19T09:09:21.676+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-07-19T09:09:21.676+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-07-19T09:09:21.676+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-07-19T09:09:21.676+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-07-19T09:09:21.703+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local --name arrow-spark /plugins/pyspark.py. Error code is: 1.
[2024-07-19T09:09:21.705+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=example_spark_operator, task_id=python_job, execution_date=20240718T000000, start_date=20240719T090920, end_date=20240719T090921
[2024-07-19T09:09:21.726+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task python_job (Cannot execute: spark-submit --master yarn --conf spark.master=local --name arrow-spark /plugins/pyspark.py. Error code is: 1.; 2207)
[2024-07-19T09:09:21.746+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-19T09:09:21.761+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
